name: luustra
favicon: null
layout_spectrum: 0.28433
typography_spectrum: 0.16
title: ༜ｌｕｕｓｔｒａ༜
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c1c4c9'
    - '#435e72'
    - '#6f7e8d'
    - '#eeeff3'
    - '#02263b'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
